spring:
  application:
    name: facility-reservation
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    data: classpath:/data.sql
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
  h2:
    console:
      enabled: true
      settings.web-allow-others: false
  security:
    user:
      name: admin
      password: password
